module.exports.itemType = {
  0: 'None',
  1: 'Currency',
  2: 'Armor',
  3: 'Weapon',
  7: 'Message',
  8: 'Engram',
  9: 'Consumable',
  10: 'ExchangeMaterial',
  11: 'MissionReward',
  12: 'QuestStep',
  13: 'QuestStepComplete',
  14: 'Emblem',
  15: 'Quest',
  16: 'Subclass',
  17: 'ClanBanner',
  18: 'Aura',
  19: 'Mod',
};

module.exports.itemSubType = {
  0: 'None',
  1: 'Crucible',
  2: 'Vanguard',
  5: 'Exotic',
  6: 'AutoRifle',
  7: 'Shotgun',
  8: 'Machinegun',
  9: 'HandCannon',
  10: 'RocketLauncher',
  11: 'FusionRifle',
  12: 'SniperRifle',
  13: 'PulseRifle',
  14: 'ScoutRifle',
  16: 'Crm',
  17: 'Sidearm',
  18: 'Sword',
  19: 'Mask',
  20: 'Shader',
};

module.exports.classType = {
  0: 'Titan',
  1: 'Hunter',
  2: 'Warlock',
};
